restaurant/blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name="blog"

urlpatterns = [
    path("",views.blog_list,name="blog_list"),  
    path("<int:id>",views.blog_detail,name="blog_detail"),
    path("tag/<slug:tag>",views.blog_tag,name="tag"),
    path("category/<slug:category>",views.blog_category,name="category"),
    path("search/",views.search,name="search"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/foods/urls.py
from django.urls import path
from .import views

app_name = "foods"

urlpatterns = [
    path("",views.food_list,name="food_list"),
    path("<int:id>",views.food_detail,name="food_detail")
]

restaurant/reservation/urls.py
from django.urls import path
from . import views

app_name = "reservation"

urlpatterns = [
    path('',views.reserve,name="reserve")
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import redirect



urlpatterns = [
    path('', lambda request: redirect('/home/')),
    path('admin/', admin.site.urls),
    path('home/', include('foods.urls')),
    path('book/', include('reservation.urls')),
    path("blog/", include("blog.urls")),
    path('rule/', TemplateView.as_view(template_name="rule.html")),
    
]

urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

restaurant/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from ckeditor.fields import RichTextField


class Blog (models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    discription = models.CharField(_("توضیحات"), max_length=100)
    content = RichTextField()
    created_at = models.DateTimeField(_("تاریخ انتشار"), default=timezone.now)
    author = models.ForeignKey(User, verbose_name=_("نویسنده"), on_delete=models.CASCADE)
    image = models.ImageField(_("تصویر"), upload_to="blogs/", blank = True , null = True)
    category = models.ForeignKey("Category", related_name="blog", verbose_name=_("دسته بندی"), on_delete=models.CASCADE, blank = True , null = True)
    tags = models.ManyToManyField("Tag", verbose_name=_("تگ ها"),related_name="blogs", blank = True , null = True)
    def __str__(self):
        return self.title

class Category (models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title
    
class Tag(models.Model):
    title = models.CharField(_("عنوان"), max_length=50)
    slug = models.SlugField(_("عنوان لاتین"))
    published_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(_("تاریخ انتشار"), auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title
    
class Comments(models.Model):
    blog = models.ForeignKey("blog", related_name="comments", verbose_name=_("مقاله"), on_delete=models.CASCADE, blank = True , null = True)
    name = models.CharField(_("نام کاربر"), max_length=50)
    email = models.EmailField(_("پست الکترونیکی"), max_length=100)
    message = models.TextField(_("متن"))
    date = models.DateTimeField(_("تاریخ انتشار"), auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.email

restaurant/contact/models.py
from django.db import models

# Create your models here.

restaurant/foods/models.py
from django.db import models
from django.utils.translation import gettext as _
# Create your models here.
class Food(models.Model):
    FOOD_TYPE=[
        ("breakefast","صبحانه"),
        ("dinner","ناهار"),
        ("lunch","شام"),
        ("drinks","نوشیدنی"),
    ]
    name = models.CharField(max_length=100, default='Default Name')
    discription = models.CharField(_("توضیحات"), max_length=100)
    rate = models.IntegerField(("امتیاز"), default=0)
    time = models.IntegerField(("زمان پخت"), blank = True , null = True)
    price = models.IntegerField()
    pub_date = models.DateField(("زمان انتشار"), auto_now=False, auto_now_add=True)
    photo = models.ImageField(upload_to='foods/', default='default.jpg')
    type_food = models.CharField(_("نوع غذا"),max_length=10,choices=FOOD_TYPE,default="drinks")
   
    def __str__(self):
        return self.name

   

restaurant/reservation/models.py
from django.db import models
from django.utils.translation import gettext as _

class Reservation(models.Model):
    name = models.CharField(_("نام و نام خانوادگی"), max_length=50)
    email = models.EmailField(_("پست الکترونیکی"), max_length=50)
    phone = models.IntegerField(_("شماره همراه"), max_length=13)
    number = models.IntegerField(_("تعداد"), max_length=50)
    date = models.DateField(_("تاریخ"), auto_now=False, auto_now_add=False)
    time = models.TimeField(_("ساعت"), auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.name

restaurant/blog/forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(widget=forms.Textarea)

restaurant/reservation/forms.py
from django import forms
from . models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = "__all__"

restaurant/blog/views.py
from django.shortcuts import render
from .models import Blog , Tag , Category , Comments
from .forms import CommentForm
from django.core.paginator import Paginator


def blog_list(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 3)  
    page_number = request.GET.get("page")
    blog_list = paginator.get_page(page_number)




    context = {
        "blog_list":blog_list
    }

    return render(request,"blog/blog_list.html",context)

def blog_detail(request,id):
    blog = Blog.objects.get(id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recents = Blog.objects.all().order_by("-created_at")[:5]
    categories = Category.objects.all()
    comments = Comments.objects.all().filter(blog=blog)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            new_name = form.cleaned_data['name']
            new_email = form.cleaned_data["email"]
            new_message = form.cleaned_data["message"]

            new_comment = Comments(blog=blog,name=new_name,email=new_email,message=new_message)
            new_comment.save()
            
    context = {
        "blog":blog,
        "tags":tags,
        "recents":recents,
        "categories":categories,
        "comments":comments,
    }
    
    return render(request,"blog/blog_detail.html",context)

def blog_tag(request,tag):
    blogs = Blog.objects.filter(tags__slug=tag)

    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog_list.html",context)

def blog_category(request,category):
    blogs = Blog.objects.filter(category__slug=category)

    context = {
        "blogs":blogs
    }
    return render(request,"blog/blog_list.html",context)

def search(request):
    if request.method == "GET":
        q = request.GET.get("search")
    blog_list = Blog.objects.filter(title__icontains=q)   
    return render(request,"blog/blog_list.html",{"blog_list":blog_list})

restaurant/contact/views.py
from django.shortcuts import render

# Create your views here.

restaurant/foods/views.py
from django.shortcuts import render
from .models import Food

def food_list(request):
    food_list = Food.objects.all()
    context = {
        "foods" : food_list
    }
    return render(request,"foods/home.html",context)

def food_detail(request , id):
    food = Food.objects.get(id = id)
    context = {
        "food":food
    }
    return render(request,"foods/detail.html",context)

restaurant/reservation/views.py
from django.shortcuts import render
from .forms import ReservationForm

def reserve(request):
    reserve_form = ReservationForm()
    if request.method == "POST":
        reserve_form = ReservationForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()
    else:
        reserve_form = ReservationForm()
    context = {
        "form":reserve_form,
    }

    return render(request,"reservation/reservation.html",context)

restaurant/blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .heading-title {
      font-family: 'Vazirmatn', sans-serif;
      margin-top: 90px;
    }
    .heading-title .page-title {
      font-family: 'Amiri', sans-serif;
      font-weight: 900;
      font-size: 40px;
    }
    .inner-blog-detail {
      text-align: right;
      direction: rtl;
    }
    .blog-comment-box {
      text-align: right;
      direction: rtl;
    }
    .comment-item-right {
      direction: rtl;
      text-align: right;
      padding-top: 30px;
      display: flex;
      flex-direction: column;
      flex: 1;
    }
    .comment-item {
      display: flex;
      gap: 15px; /* Increased gap for better spacing */
      border: 1px solid #ccc;
      border-radius: 15px;
      padding: 15px;
      margin-bottom: 20px;
      background-color: #fdfdfd;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
      align-items: flex-start;
    }
    .comment-item-left img {
      width: 60px;
      height: 60px;
      border-radius: 50%;
      object-fit: cover;
    }
    .right-btn-re {
      font-family: 'Vazirmatn', sans-serif;
      font-style: normal;
      align-self: flex-end;
      margin-top: 10px; /* Adjusted margin */
      color: #007bff;
      text-decoration: none;
      font-size: 14px;
    }
    .comment-item .pull-left {
      direction: ltr;
      text-align: left;
    }
    .comment-item .des-l {
      text-align: justify;
      margin-top: 17px;
    }
    .blog-tag-box {
      text-align: right;
      direction: rtl;
    }
    .img-fluid-original {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }
  </style>

  <div class="blog-box">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="heading-title text-center">
            <h2 class="page-title">{{ blog.title }}</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-8 col-lg-8 col-12">
          <div class="blog-inner-details-page">
            <div class="blog-inner-box">
              <div class="side-blog-img">
                <img class="img-fluid-original" src="{{ blog.image.url }}" alt="" />
                <div class="date-blog-up">{{ blog.created_at|date:'d b' }}</div>
              </div>
              <div class="inner-blog-detail details-page">
                <h3>{{ blog.discription|safe }}</h3>
                <ul>
                  <li>
                    <i class="zmdi zmdi-account"></i>پست شده توسط : <span>{{ blog.author }}</span>
                  </li>
                  <li>|</li>
                  <li>
                    <i class="zmdi zmdi-time"></i>زمان انتشار : <span>{{ blog.created_at|time }}</span>
                  </li>
                </ul>
                <p dir="rtl">{{ blog.content|safe }}</p>
              </div>
            </div>
            <div class="blog-comment-box">
              <h3>نظرات</h3>

              {% for cm in comments %}
                <div class="comment-item">
                  <div class="comment-item-left">
                    <img src="\static\images\avt-img.jpg" alt="" />
                  </div>
                  <div class="comment-item-right">
                    <div class="pull-right">
                      <a class="cm-name" href="">{{ cm.name }}</a>
                    </div>
                    <div class="pull-left">
                      <i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{ cm.date }}</span>
                    </div>
                    <div class="des-l">
                      <p>{{ cm.message }}</p>
                    </div>
                    <a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> پاسخ</a>
                  </div>
                </div>
              {% endfor %}
              <style>
                .comment-respond-box {
                  text-align: right;
                  direction: rtl;
                }
                .form-group {
                  border-radius: 50px;
                  border: #007bff;
                }
              </style>
            </div>
            <div class="comment-respond-box">
              <h3>نظر شما در این مورد چیه؟</h3>
              <div class="comment-respond-form">
                <form id="commentrespondform" class="comment-form-respond row" method="post">
                  {% csrf_token %}
                  <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="form-group">
                      <input id="name_com" class="form-control" name="name" placeholder="نام" type="text" style="border-radius: 8px;" />
                    </div>
                    <div class="form-group">
                      <input id="email_com" class="form-control" name="email" placeholder="پست الکترونیک" type="email" style="border-radius: 8px;" />
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="form-group">
                      <textarea class="form-control" name="message" id="textarea_com" placeholder="پیام شما" rows="2" style="border-radius: 8px;"></textarea>
                    </div>
                  </div>
                  <div class="col-lg-12 col-md-12 col-sm-12">
                    <button type="submit" style="border-radius: 8px;" class="btn btn-submit">ثبت نظر</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
          <div class="right-side-blog" style="text-align: right; direction: rtl;">
            <h3>جستجو</h3>
            <form method="GET" action="{% url 'blog:search' %}">
              <div class="blog-search-form">
                <input name="search" placeholder="جستجوی مقاله مورد نظر" type="text" style="border-radius: 8px;" />
                <button class="search-btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
              </div>
            </form>
            <h3>دسته بندی</h3>
            <div class="blog-categories">
              <ul>
                {% for cat in categories %}
                  <li>
                    <a href="{% url 'blog:category' cat.slug %}"><span>{{ cat.title }}</span></a>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <h3>پست های اخیر</h3>
            <div class="post-box-blog">
              <div class="recent-post-box">
                <style>
                  .recent-box-blog {
                    display: grid;
                    flex-direction: column;
                    gap: 1rem;
                    border: 1px solid #ccc;
                    border-radius: 15px;
                    padding: 10px;
                  }
                  .img-fluid-recent {
                    display: flex;
                    align-items: center;
                    gap: 10px;
                    border: 1px solid #ccc;
                    border-radius: 15px;
                    padding: 5px;
                    transition: background-color 0.3s ease;
                  }
                  .img-fluid-recent img {
                    width: 80px;
                    height: 80px;
                    object-fit: cover;
                    border-radius: 1000px;
                  }
                  .img-fluid-recent:hover {
                    background-color: #8b4513;
                    border-radius: 8px;
                  }
                </style>
                {% for blog in recents %}
                  <div class="recent-box-blog">
                    <div class="recent-img">
                      <img class="img-fluid-recent" src="{{ blog.image.url }}" style="height: 100px;" alt="" />
                    </div>
                    <div class="recent-info" style="margin-right: 8px;">
                      <h4 style="margin-top: 0px;">{{ blog.discription }}</h4>
                      <ul style="margin-bottom: 4px;">
                        <li>
                          <i class="zmdi zmdi-account"></i>Posted By : <span>{{ blog.author }}</span>
                        </li>
                        <li>|</li>
                        <li>
                          <i class="zmdi zmdi-time"></i>Time : <span>{{ blog.created_at|time }}</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>

            <div class="blog-tag-box">
              <h3>تگ های اخیر</h3>
              <ul class="list-inline tag-list">
                {% for tag in tags %}
                  <li class="list-inline-item">
                    <a href="{% url 'blog:tag' tag.slug %}">{{ tag.title }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <style>
    .contact-imfo-box {
      padding-top: 16px;
      padding-bottom: 16px;
      margin-top: 0;
      margin-bottom: 0;
    }
    .contact-imfo-box .lead {
      font-family: 'Vazirmatn', sans-serif;
    }
    
    .contact-imfo-box .col-md-4 {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
      text-align: right;
      direction: rtl;
    }
    
    .contact-imfo-box i {
      font-size: 28px;
      background-color: white;
      border-radius: 50%;
      width: 50px;
      height: 50px;
      line-height: 50px;
      text-align: center;
      color: #c69c6d;
      flex-shrink: 0;
      transition: transform 0.3s ease, box-shadow 0.3s ease;
      animation: popIn 0.6s ease;
    }
    
    @keyframes popIn {
      0% {
        transform: scale(0.8);
        opacity: 0;
      }
      100% {
        transform: scale(1);
        opacity: 1;
      }
    }
    
    .contact-imfo-box i:hover {
      transform: scale(1.2) rotate(5deg);
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }
    
    .contact-imfo-box .overflow-hidden {
      margin: 0;
    }
    
    .contact-imfo-box h4 {
      margin: 0 0 5px;
    }
    
    .contact-imfo-box p {
      margin: 0;
      font-size: 15px;
    }
  </style>

  <div class="contact-imfo-box" id="contact-section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fa fa-volume-control-phone"></i>
          <div class="overflow-hidden" style="text-align: center; direction: rtl;">
            <h4>تماس</h4>
            <p class="lead" style="font-size: 20px; font-weight: 100;">5781 038 910 98+</p>
          </div>
        </div>
        <div class="col-md-4">
          <i class="fa fa-envelope"></i>
          <div class="overflow-hidden" style="text-align: center; direction: rtl;">
            <h4>پست الکترونیک</h4>
            <p class="lead" style="font-size: 20px; font-weight: 100;">soheil.ce.99@gmail.com</p>
          </div>
        </div>
        <div class="col-md-4">
          <i class="fa fa-map-marker"></i>
          <div class="overflow-hidden">
            <h4 style="text-align: center; direction: rtl;">نشانی</h4>
            <a href="https://maps.app.goo.gl/64LK4VYf1nwnE2bB6" target="_blank" style="font-size: 18px;font-family: 'Vazirmatn', sans-serif; font-weight: 100; text-decoration: none; color:rgb(255, 255, 255);">سمنان، میدان سعدی، بلوار 17 شهریور</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

restaurant/blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- Start slides -->
  <style>
    #slides h1,
    #slides p {
      font-family: 'El Messiri', sans-serif;
    }
  </style>
  <div id="slides" class="cover-slides">
    <ul class="slides-container">
      <li class="text-center">
        <img src="/media/foods/blog-slider1.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
      <li class="text-center">
        <img src="/media/foods/blog-slider2.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
      <li class="text-center">
        <img src="/media/foods/blog-slider3.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
      <li class="text-center">
        <img src="/media/foods/blog-slider4.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
      <li class="text-center">
        <img src="/media/foods/blog-slider5.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
      <li class="text-center">
        <img src="/media/foods/blog-slider6.jpg" alt="" />
        <div class="container">
          <div class="row"></div>
        </div>
      </li>
    </ul>
    <div class="slides-navigation">
      <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
      <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    </div>
  </div>
  <!-- End slides -->

  <!-- Start blog -->

  <style>
    .blog-box .blog-title {
      font-family: 'El Messiri', sans-serif;
      font-size: 40px;
      font-weight: 600;
    }
  </style>

  <div class="blog-box">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="heading-title text-center">
            <h2 class="blog-title" style="text-align: right; direction:rtl;">مجله یامی فود</h2>
          </div>
        </div>
      </div>
      <style>
        .col-lg-4 .blog-detail {
          text-align: right;
          direction: rtl;
          width: 350px;
          height: 420px;
        }
      </style>
      <div class="row">
        {% for blog in blog_list %}
          <div class="col-lg-4 col-md-6 col-12">
            <div class="blog-box-inner">
              <div class="blog-img-box">
                <img class="img-fluid" src="/media/foods/paszamine.jpg" style="height: 420px;" alt="" />
              </div>
              <div class="blog-detail">
                <h4>{{ blog.title|safe }}</h4>
                <ul>
                  <li>
                    <span>{{ blog.author }}</span>
                  </li>
                  <li>|</li>
                  <li>
                    <span>{{ blog.created_at|date:' Y b d ' }}</span>
                  </li>
                </ul>
                <p dir="rtl">{{ blog.content|truncatewords_html:50|safe }}</p>
                <a class="btn btn-lg btn-circle btn-outline-new-white" href=" {% url 'blog:blog_detail' blog.id %}">بیشتر بخوانید</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- End blog -->

  <!-- Pagination -->

  {% if blog_list.has_other_pages %}
    <div class="container mb-4">
      <div class="row">
        <div class="col d-flex justify-content-center">
          <nav aria-label="Page navigation">
            <ul class="pagination custom-pagination">
              {% if blog_list.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page=1">اولین</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ blog_list.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
                </li>
              {% endif %}

              {% for page in blog_list.paginator.page_range %}
                {% if blog_list.number == page %}
                  <li class="page-item active">
                    <span class="page-link">{{ page }}</span>
                  </li>
                {% elif page >= blog_list.number|add:'-2' and page <= blog_list.number|add:'2' %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                  </li>
                {% endif %}
              {% endfor %}

              {% if blog_list.has_next %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ blog_list.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="?page={{ blog_list.paginator.num_pages }}">آخرین</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  {% endif %}

  <style>
    .custom-pagination .page-link {
      border: none;
      margin: 0 3px;
      color: #333;
      border-radius: 8px;
      transition: all 0.2s ease-in-out;
      padding: 6px 12px;
      background-color: #f8f9fa;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
    }
    
    .custom-pagination .page-link:hover {
      background-color: #e2e6ea;
      color: #007bff;
    }
    
    .custom-pagination .active .page-link {
      background-color: #007bff;
      color: #fff;
      font-weight: bold;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
    }
    
    .custom-pagination .page-item.disabled .page-link {
      color: #ccc;
      pointer-events: none;
      background-color: #f1f1f1;
    }
  </style>

  <!-- Start Contact info -->
  <style>
    .contact-imfo-box {
      padding-top: 16px;
      padding-bottom: 16px;
      margin-top: 0;
      margin-bottom: 0;
    }
    .contact-imfo-box .lead {
      font-family: 'Vazirmatn', sans-serif;
    }
    
    .contact-imfo-box .col-md-4 {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px; /* فاصله بین آیکون و متن */
      text-align: right;
      direction: rtl;
    }
    
    .contact-imfo-box i {
      font-size: 28px;
      background-color: white;
      border-radius: 50%;
      width: 50px;
      height: 50px;
      line-height: 50px;
      text-align: center;
      color: #c69c6d;
      flex-shrink: 0;
      transition: transform 0.3s ease, box-shadow 0.3s ease;
      animation: popIn 0.6s ease;
    }
    
    /* انیمیشن اولیه موقع لود */
    @keyframes popIn {
      0% {
        transform: scale(0.8);
        opacity: 0;
      }
      100% {
        transform: scale(1);
        opacity: 1;
      }
    }
    
    /* افکت هاور */
    .contact-imfo-box i:hover {
      transform: scale(1.2) rotate(5deg);
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
    }
    
    .contact-imfo-box .overflow-hidden {
      margin: 0;
    }
    
    .contact-imfo-box h4 {
      margin: 0 0 5px;
    }
    
    .contact-imfo-box p {
      margin: 0;
      font-size: 15px;
    }
  </style>

  <div class="contact-imfo-box" id="contact-section">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fa fa-volume-control-phone"></i>
          <div class="overflow-hidden" style="text-align: center; direction: rtl;">
            <h4>تماس</h4>
            <p class="lead" style="font-size: 20px; font-weight: 100;">5781 038 910 98+</p>
          </div>
        </div>
        <div class="col-md-4">
          <i class="fa fa-envelope"></i>
          <div class="overflow-hidden" style="text-align: center; direction: rtl;">
            <h4>پست الکترونیک</h4>
            <p class="lead" style="font-size: 20px; font-weight: 100;">soheil.ce.99@gmail.com</p>
          </div>
        </div>
        <div class="col-md-4">
          <i class="fa fa-map-marker"></i>
          <div class="overflow-hidden">
            <h4 style="text-align: center; direction: rtl;">نشانی</h4>
            <a href="https://maps.app.goo.gl/64LK4VYf1nwnE2bB6" target="_blank" style="font-size: 18px;font-family: 'Vazirmatn', sans-serif; font-weight: 100; text-decoration: none; color:rgb(255, 255, 255);">سمنان، میدان سعدی، بلوار 17 شهریور</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- End Contact info -->
{% endblock %}